# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aS73olsrhGxe7hBPu2eH6OVEPnIu9Y-W
"""

def add(a, b):
  return a + b

if __name__ == "__main__":
  print(f"2 + 3 = {add(2,3)}")