# -*- coding: utf-8 -*-
"""test_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nnVZauF7bFFchEHBRjQOr9Lodvy8Bpt6
"""

from app import add

def test_add():
  assert add(2,3) == 5